### ISSUE TITLE
Export MOSES models to the atomspace

### ISSUE THREAD

**Issue by ngeiswei** [opencog/agi-bio#10]
This issue encompasses exporting the models + their fitness semantics, that is what the score of a model means, and how this model relates to the target feature.
- [X] Export models
- [ ] Export fitness information
  - [X] Accuracy and balanced accuracy (the semantics of those are let aside for now)
  - [ ] Semantics of accuracy and balanced accuracy (need to import the dataset for that)

**Comment by ngeiswei** [comment]
The following #12 completes that task

**Comment by mjsduncan** [comment]
outdated
