### ISSUE TITLE
Add Aging/Mythelation Genes to Atomspace

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#11]
Per Bobby:
Can we include Table S6 from this paper as an additional gene list, similar to the ones from mSigDB?  http://www.sciencedirect.com/science/article/pii/S1097276512008933

This is a list of genes that seem to be modulated with the epigenetic clock of aging that has been shown to work very repeatedly and across different tissues...  I don't think it's already included within mSigDB though.  

Here's the data: https://drive.google.com/file/d/0B3NYFAN330UTbDdBTC1RNngyV0l3cVRRVVY4cFdKRDZLR0dj/view?usp=sharing

Selam, This set can be represented similar to how the MSigDB gene sets are represented. 
Lets create a new general ConceptNode "GeneSet" that this gene set inherits from.
And then in the MSigDB representation, we should add an inheritance of MSigDB_GeneSet to GeneSet, IOW:

```
InheritanceLink
  ConceptNode "MSigDB_GeneSet"
  ConceptNode "GeneSet"
```

Fill in as many of the fields used in the MSigDB that can also be applied to this gene set. Perhaps Meseret can help if needed with interpreting things from the article regarding what the field values should be.

**Comment by eddiemonroe** [comment]
Selam, here's what I'm thinking for representation:

    InteritanceLink
      ConceptNode "Aging-Mythelation_GeneSet"
      ConceptNode "GeneSet"

    EvaluationLink
      PredicateNode "organism_of"
      ListLink
        ConceptNode "Aging-Mythelation_GeneSet"
        ConceptNode "Homo sapiens"

    EvaluationLink
      PredicateNode "source_PubMedID"
      ListLink 
        ConceptNode "Aging-Mythelation_GeneSet"
        NumberNode #23177740

And then for each gene:

    MemberLink
      GeneNode "ABCA3"
      ConceptNode "Aging-Mythelation_GeneSet"

**Comment by mjsduncan** [comment]
outdated
