### ISSUE TITLE
Lifespan Observations Gene Sets --> atomspace

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#16]
Identify human homolog genes.
Import into atomspace
Supply list of the homolog genes for Bobby

**Comment by eddiemonroe** [comment]
representation spec: https://docs.google.com/document/d/1rYDcpzLSNQ1B4-eV4QAmpZmhFTZX9mOzLAFFbbLbtQQ/edit#heading=h.azflnmlg9cla

homologous genes: https://drive.google.com/file/d/0B3NYFAN330UTSGNPRlBWc0w0SGo3WVQtMXdFdHVzU3hidHdN/view?usp=sharing

**Comment by mjsduncan** [comment]
outdated
