### ISSUE TITLE
Selam Misc Items

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#18]
[ ] confirm Amen's docker for bio project is working - https://github.com/opencog/agi-bio/pull/9
[ ] script to load all atom scheme files in a directory
[ ] put bio atomspace scheme representations up in its own repo or on a server where others can access

**Comment by zselam** [comment]
1. Run the following from agi-bio/bioscience will build Amen's dockerfile for bio project 
      $ docker build --rm=true .
2. Python script to all bio scheme files in a directory 
    agi-bio/knowledge-import/load_atoms.py
3. All bio scheme files are in agi-bio/ scheme-representation.

**Comment by mjsduncan** [comment]
outdated
