### ISSUE TITLE
GO Ontology -> Atomspace import script

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#2]
Per specifications in the Google doc.

Target Date: (Selam, please fill in)
- [x] What are the # of atoms and RAM required for full GO (ontology db) import
- [x] Load onto cogserver on Hetzner along with the MSigDB (if they both fit without backing store)
- [x] RO representation in GO (Eddie - assigned to #31)
- [x] intersection_of and typedef representation (Eddie - assigned to #7)

**Comment by zselam** [comment]
Total number of atoms   -- 532159  
Loading took 0.68 minute using computer with 4GB RAM
