### ISSUE TITLE
Updated MOSES Models for Import (Mike/Meseret)

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#20]
For all relevant models we want included in the bio atomspace, especially the nonagenarian models, but for supercentenarians, etc. as well.

These should be in the format  Mike specified for the latest conversion script of Nil's that includes model accuracy information for conversion to atomspace truth values.

The models should be delivered to Selam for importing with the latest script from Nil.

**Comment by mjsduncan** [comment]
outdated
