### ISSUE TITLE
Fix parens in EvaluationLinks

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#33]
There should be an end parenthesis after PredicateNodes in EvaluationLinks like this:

```
(EvaluationLink
         (PredicateNode "GO_namespace")
         (ListLink
                 (ConceptNode "GO:0000007")
                 (ConceptNode "molecular_function")))
```

I fixed this for GO terms and GO annotations (https://github.com/opencog/agi-bio/commit/20298375b31a5ab2416e03e733dadfad6d1f7f39). Please fix for the other knowledge bases where needed and regenerate the scheme files.

**Comment by ceefour** [comment]
(As part of [OpenCog Neo4j GSoC 2015 project](http://ceefour.github.io/opencog-neo4j/) [thread](https://groups.google.com/d/msgid/opencog/313645d0-58f7-4588-b164-97578126abfe%40googlegroups.com?utm_medium=email&utm_source=footer) ) This is what `EvaluationLink` actually look like in the `.scm` dumps:

```scheme
(EvaluationLink 
	 (PredicateNode "annotation"
		 (ListLink 
			 (GeneNode "LOC101930168")
			 (ConceptNode "0005215"))
	 )
)
```

However this is incorrect according to OpenCog Wikis, which should be

```scheme
(EvaluationLink 
	 (PredicateNode "annotation")
	 (ListLink 
		 (GeneNode "LOC101930168")
		 (ConceptNode "0005215"))
)
```

For now I make a hardcoded assumption in the importer to workaround the incorrect structure.
The proper way to deal with this as suggested by @AmeBel :

1. fix Bio_schemeFiles for good
2. fail with diagnostic message

Tag myself for this.

**Comment by ceefour** [comment]
I think all the Python scripts have been fixed, just need to regenerate the `.scm` files.

**Comment by ceefour** [comment]
When these pull requests have merged, I think this issue can be closed as fixed:

1. https://github.com/opencog/agi-bio/pull/57
2. https://github.com/opencog/agi-bio/pull/58
3. https://github.com/opencog/agi-bio/pull/59
4. https://github.com/opencog/test-datasets/pull/35
5. https://github.com/opencog/test-datasets/pull/36

**Comment by mjsduncan** [comment]
outdated
