### ISSUE TITLE
GO.scm - escape char causes it to choke

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#45]
The escape character in this term name is causing loading of the scheme file to choke, and then the rest of the atoms following are not loaded:

```
 805491 (EvaluationLink
 805492          (PredicateNode "GO_name")
 805493          (ListLink
 805494                  (ConceptNode "GO:0033942")
 805495                 ; (ConceptNode "4-alpha-D-\{(1->4)-alpha-D-glucano}trehalose trehalohydrolase activity")
 805496                  (ConceptNode "4-alpha-D-{(1->4)-alpha-D-glucano}trehalose trehalohydrolase activity")
 805497          )
 805498 )
```

Also, the latest version of GO.scm checked in the repo has trailing spaces after some of the GO term ConceptNode names. This was causing problems in inheritance mining and will also cause problems with reasoning. I regenerated the scheme file by running the python script and the trailing spaces are no longer there... Perhaps the repo version was generated from an older version of the python script?

**Comment by ngeiswei** [comment]
Oh, interesting observation.

Yes, the GO.scm file is old, I actually have a branch with the new one. https://github.com/ngeiswei/agi-bio/tree/update-scheme-representation

**Comment by eddiemonroe** [comment]
Thanks, Nil. I just pushed a current version to the master branch that
includes a temp fix for the escape character.

**Comment by zselam** [comment]
GO_scm.py updated , fix escape character causing loading error ...
