### ISSUE TITLE
Duplicates in GO_annotations.scm

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/agi-bio#47]
Looks like there are a lot of duplicate MemberLinks in GO_annotations.scm

For example

```
(MemberLink
        (GeneNode "TLR8")
        (ConceptNode "GO:0010008"))
has a bunch of entries
```

These won't add additional atoms to the atomspace I'm pretty sure, but it's probably slowing down loading the scheme file considerably.

**Comment by mjsduncan** [comment]
this version if the import script is archived
