### ISSUE TITLE
build fail due to refactoring

### ISSUE THREAD

**Issue by mjsduncan** [opencog/agi-bio#60]
i tried to build opencog with the "bioscience" module.  after changing the directory to match current location of "Module.h" in BioScienceTypes.cc (commit 2b8b5) the build still fails because because there is no longer a file "opencog/atomspace/atom_types.cc".  anyone know what replaced this file?

**Comment by AmeBel** [comment]
https://github.com/opencog/atomspace/blob/master/opencog/atoms/base/atom_types.cc

**Comment by eddiemonroe** [comment]
@mjsduncan the easiest way to add the custom bio atom types is to add GeneNode and ProteinNode to 

atomspace/opencog/atoms/base/atom_types.script

like so:

// Custom atom types for the agi-bio project
GENE_NODE <- NODE
PROTEIN_NODE <- NODE

With more people working on the biopace now, perhaps we should add these as atom types in the atomspace master branch? what do you think @bgoertzel? People keep getting tripped up on this. 

I guess alternatively, Gene and Protein could be defined as ConceptNodes and inherited from for the instances.

**Comment by eddiemonroe** [comment]
Or maybe we could have a custom_atom_types.script file that automatically gets pulled in. It starts off with no entries (in master) and a comment on top like //Define your custom atom types here

**Comment by mjsduncan** [comment]
eddie, i'm still trying to get the build to work with the latest opencog code, can atom_types.script be added without building bioscience in to opencog?

**Comment by mjsduncan** [comment]
thanks, ambel! i pushed 9219b64 to fix the include path and now i get this:
````
Scanning dependencies of target bioscience-types
[100%] Building CXX object bioscience/types/CMakeFiles/bioscience-types.dir/BioScienceTypes.cc.o
/opencog/bioscience/types/BioScienceTypes.cc:32:15: error: expected constructor, destructor, or type conversion be
fore ‘(’ token
 TRIVIAL_MODULE(BioScienceTypesModule)
               ^
/opencog/bioscience/types/BioScienceTypes.cc: In function ‘opencog::Module* opencog_module_load(opencog::CogServer
&)’:
/opencog/bioscience/types/BioScienceTypes.cc:33:171: error: expected type-specifier before ‘BioScienceTypesModule’
 DECLARE_MODULE(BioScienceTypesModule)

                                                         ^

/opencog/bioscience/types/BioScienceTypes.cc:33:171: error: expected ‘;’ before ‘BioScienceTypesModule’
/opencog/bioscience/types/BioScienceTypes.cc:33:202: error: ‘BioScienceTypesModule’ was not declared in this scope
 DECLARE_MODULE(BioScienceTypesModule)

                                                                                        ^
/opencog/bioscience/types/BioScienceTypes.cc: At global scope:
/opencog/bioscience/types/BioScienceTypes.cc:33:290: error: ‘BioScienceTypesModule’ has not been declared
 DECLARE_MODULE(BioScienceTypesModule)


                                                              ^
/opencog/bioscience/types/BioScienceTypes.cc: In function ‘opencog::Module* opencog_module_load(opencog::CogServer
&)’:
/opencog/bioscience/types/BioScienceTypes.cc:33:205: warning: control reaches end of non-void function [-Wreturn-t
ype]
 DECLARE_MODULE(BioScienceTypesModule)

                                                                                           ^
make[2]: *** [bioscience/types/CMakeFiles/bioscience-types.dir/BioScienceTypes.cc.o] Error 1
make[1]: *** [bioscience/types/CMakeFiles/bioscience-types.dir/all] Error 2
````

**Comment by eddiemonroe** [comment]
@mjsduncan, yes, i believe if you add the entries to atom_types.script, then you no longer need to build bioscience with opencog. Much easier.

@AmeBel does that sound right to you? that adding the entries to atom_types.script should be sufficient for creating the custom atom type?

**Comment by AmeBel** [comment]
Looking into it.

**Comment by AmeBel** [comment]
Suggested solution @ https://github.com/opencog/agi-bio/pull/62

**Comment by mjsduncan** [comment]
thanks, amen!  it builds now.  eddie, in atom_types.script does `PROTEIN_NODE <- CONCEPT_NODE` mean a proteinNode "x" is a conceptNode "x" that inherits from conceptNode "protein"? can other types of nodes be defined arbitrarily?  can links be defined?  i'll close this issue but eddie if you reply by starting another issue i'll use your answer to expand the read-me.

**Comment by bgoertzel** [comment]
Mike: PROTEIN_NODE <- CONCEPT_NODE just means that a proteinNode is a conceptNode, just like saying Float <- Number ... it has nothing to do with conceptnodes named "protein"

**Comment by mjsduncan** [comment]
so what's the difference between (proteinNode "x") and (conceptNode "x") ?  are they different "types" of conceptNodes?

**Comment by eddiemonroe** [comment]
Mike, I wonder if you're confusing types and instances?  Atom types inherit hierarchically, and the notation for defining atom types is CHILD TYPE <- PARENT TYPE

PROTEIN_NODE <- CONCEPT_NODE <- NODE <- ATOM

So every ProteinNode is technically also a ConceptNode, every ConceptNode is a Node, and everything is an Atom.

(ProteinNode "x") is an instance of a ProteinNode. But it's also (technically) a ConceptNode, Node, and Atom because of the type inheritance.

**Comment by mjsduncan** [comment]
i'm trying to get a clear definition of proteinNode.  if a proteinNode "x" is defined does that mean that conceptNode "x" exists and i can define geneNode "x" that inherits from conceptNode "x" as well?

**Comment by eddiemonroe** [comment]
No. Creating an instance of a type does not mean that instances of the parent types with the same name automatically exist.

If you create ProteinNode "x", there is not a ConceptNode "x" that automatically exists (unless ConceptNode "x" was explicitly created elsewhere).

**Comment by mjsduncan** [comment]
ok, so how do you assign properties to proteinNode so that all proteinNode instances inherit those properties, and what kind of link (xLink) would you use for 'geneNode "x" expresses proteinNode "x" ' ? can i use atom_types.script to define expressesLink <- xLink ?

**Comment by eddiemonroe** [comment]
In general you want to use Predicates rather than creating new atom/link types.

For gene expression, you could do something like
```
Evaluation
    Predicate "expresses"
        List   Gene "x"  Protein "y"
```
Or whatever Ben or Nil says. :)

Check out the Bio Knowledge Atomspace Representation google doc for examples. (or other atomspace examples)

How to assign properties to the ProteinNode *type* is a more interesting question. If we didn't have the specialized atom type, and proteins were defined like so
```
Inheritance
    Concept "protein"
    Concept "protein xyz"

then we could

Inheritance
    Concept "biomolecule"
    Concept "protein"
```
and then rely on PLN to conclude that Concept "protein xyz" is also a biomolecule.

But I don't know how one would assign properties similarly at the atom type level.
@bgoertzel or @ngeiswei?

**Comment by mjsduncan** [comment]
i guess i'm really wondering what is gained by using the geneNode and proteinNode constructions :P  should we keep it going forward?

**Comment by ngeiswei** [comment]
@eddiemonroe I think you mean
```
Inheritance
    Concept "protein xyz"
    Concept "protein"

Inheritance
    Concept "protein"
    Concept "biomolecule"
```

Regarding "assigning properties similarly at the atom type level", do you mean creating atom type dynamically?

**Comment by ngeiswei** [comment]
Or do you mean specifying properties for an entire collection of atoms of a certain type? If so you'd do that with quantifiers like ForAll, Lambda, ImplicationScope, SatisfyingSetScope, etc. having the atom type specified in the variable declaration of the quantifier. But maybe that's not your question.

**Comment by eddiemonroe** [comment]
Nil, yes, meaning the latter. And I was just about to write that it could
be done with an Implication and VariableNode with Type.

(And thanks for the correction with my Inheritance dyslexia.)

But what do you think about Mike's question about the value of having the
special atom types GeneNode and ProteinNode? I guess it saves the
representation (Inheritance  Concept "gene x"  Concept "gene"), for every
gene, and the resulting PLN step needed at times. But then it seems to make
things like assigning properties at the Protein atom type level more
complex.

What would you say are the advantages and disadvantages of having atom type
GeneNode versus representing as concept nodes, that is using (Inheritance
Concept "gene-xyz"  Concept "gene")?

**Comment by ngeiswei** [comment]
I don't know. I would need to understand what makes a `GeneNode` a gene node.

Typically, as you guess, introducing a new type may allow to obtain more compact representations, possibly faster/simpler code. For instance maybe you want to have some scheme code do this or that when it encounters this particular type. You may want also to tailor PLN rules just for these types.

So you have to measure the pros and cons. Sorry for the abstract answer. ;-)

**Comment by mjsduncan** [comment]
eddie said
"I guess it saves the representation (Inheritance Concept "gene x" Concept
"gene"), for every gene, and the resulting PLN step needed at times"

but ben said
"Mike: PROTEIN_NODE <- CONCEPT_NODE just means that a proteinNode is a
conceptNode, just like saying Float <- Number ... it has nothing to do with
conceptnodes named "protein" "

i'm confused, are proteinNodes structured differently than geneNodes?

**Comment by eddiemonroe** [comment]
Mike, you're confusing and type and instance. and thus confusing atom type
inheritance and atom instance inheritance. Type and instance definitions
and inheritance are separate, 2 different things.

Atom type inheritance is defined by

PROTEIN_NODE <- CONCEPT_NODE in atom_types.script

Instance inheritance is defined in the atomspace by

(Inheritance (Concept "a") (Concept "b"))

So I was asking about the pros and cons of these two different approaches
for structuring representations of proteins and genes. make sense?

**Comment by mjsduncan** [comment]
so you're saying that to give geneNode "x" gene properties we still have to
say Inheritance geneNode "x" conceptNode "gene" ?

**Comment by eddiemonroe** [comment]
No, you could use one of the approaches Nil talked about to represent that
all GeneNodes have certain properties, that is, certain properties that all
genes share.

**Comment by eddiemonroe** [comment]
I think something like:

ForAllLink
    TypedVariableLink
         VariableNode $P
         TypeNode "ProteinNode"
    InheritanceLink
          VariableNode $P
          ConceptNode "biomolecule"

Is that right Nil or Ben?

**Comment by bgoertzel** [comment]
Eddie that looks correct...

Mike, I see the value of GeneNode and ProteinNode as being similar to the value of WordNode

These are Atom types that refer to specific types of entities outside the OpenCog software system, with names that refer to standard labels recognized outside the OpenCog software system

Of course, instead of "ProteinNode "brca1" " we could always have

InheritanceLink
      ConceptNode "Protein:brca1"
      ConceptNode "Protein"

but if we have a lot of ProteinNodes the latter representation uses more memory and processing time and is slightly less transparent...

**Comment by bgoertzel** [comment]
Also there are indexes that index Atoms by type, so getting a list of all ProteinNodes that X links to is a bit faster than getting a list of all {ConceptNodes  inheriting from (ConceptNode "Protein")) that X links to ....

**Comment by bgoertzel** [comment]
So there's nothing you can do with GeneNode / ProteinNode that you cannot do without it, but in my personal judgment it seems like a more elegant representation with a modest efficiency advantage as well

**Comment by bgoertzel** [comment]
One often hits "judgment calls" like this in knowledge representation, since there are so many equivalent representations of a given piece of knowledge..

**Comment by mjsduncan** [comment]
so in eddie's construction:
```
ForAllLink 
     TypedVariableLink VariableNode $P TypeNode "ProteinNode"
     InheritanceLink VariableNode $P ConceptNode "biomolecule"
```
do the inheritance links get put into the atomspace or is this like a program that has to be run to find them?

**Comment by linas** [comment]
The point of having ForAllLinks is to avoid explicitly adding giant masses of repetitive atoms into the atomspace. 

For me, with language, I'm getting atomspces with 100M atoms in them, and at 1KB or 2KB per atom, these run at 100GBytes RAM or more, and take hours to load and store.  You don't want to go there if you can avoid it. 

so for example, saying 
```
ProteinNode "brca1" 
``` 
instead of 
```
InheritanceLink
   ConceptNode "Protein:brca1" 
   ConceptNode "Protein"
```
will cut the size of your atomspace by HALF. That's a major win. (assuming you have millions of proteins)

Also please do NOT add PROTEIN_NODE to the core atomspace. Its almost trivial to add atom types of your own See here for an example:  https://github.com/opencog/opencog/tree/master/opencog/learning/PatternMiner/types

**Comment by mjsduncan** [comment]
thanks, linus! so do you have to invoke an AllLink when you're interested in those virtual links or is that automatic once it's been put in the atomspace?
also, when you say not to put ProteinNodes in the core are you saying not to use the agi-bio/bioscience code?

**Comment by AmeBel** [comment]
FYI @linas the types are defined @ https://github.com/opencog/agi-bio/tree/master/bioscience

**Comment by linas** [comment]
I've never used ForAllLink for anything. But then, I've never used PLN for anything, so I can't help with that.

Re PROTEIN_NODE: just cu-n-paste the code in  https://github.com/opencog/opencog/tree/master/opencog/learning/PatternMiner/types to some directory in this project, edit the atom_types.script file, remove the junk there, add PROTEIN_NODE, compile and install. That will autogenerate scheme, python and C++ bindings for your atom types.

**Comment by linas** [comment]
Never mind. per Amen's comment, looks like Eddie define ProteinNode and GeneNode in January 2015, and the code looks like it should "just plain work" so I am unclear on what this side-issue is.

**Comment by linas** [comment]
Oh, there is a remaining cut-n-paste typo: it says `nlp_types.scm` when it should say `bioscience_types.scm` in the makefile

**Comment by linas** [comment]
Eddie is correct: in general, its better to use
```
Evaluation
    Predicate "expresses"
        List   Gene "x"  Protein "y"
```
in general, but, if for some reason, you are running out of RAM, and have one very very common relation, e.g. "expresses", then you can invent a new link type and write
```
ExpressesLink
     Gene "x"  Protein "y"
```
However, this is kind of an "advanced trick" and assumes that you've done all the other paperwork needed to get everything to work with your new link types.  And all that other work can be a lot: none of it is automatic.

**Comment by ngeiswei** [comment]
Regarding `ForAll`. You may either
1. apply universal instantiation in a forward way using the forward chainer. In this mode the instances would be persistent unless you wish to erase them.
2. apply universal instantiation in a backward way using the backward chainer. In this mode they would be temporarily produced as needed to prove your target. Unless your target are the instances themselves they would not be persistent.

Another option is to use `meta-bind` to produce all instances at once

https://github.com/opencog/atomspace/blob/master/opencog/scm/opencog/rule-engine/rule-engine-utils.scm#L175

Actually I realized the ForAll rule needs work, so let me re-implement it and add an example in the opencog repository.

**Comment by ngeiswei** [comment]
Here it is https://github.com/opencog/opencog/tree/master/examples/pln/universal-instantiation
