### ISSUE TITLE
where is Lifespan-observations_2015-02-21.csv ?

### ISSUE THREAD

**Issue by mjsduncan** [opencog/agi-bio#61]
the cvs file used by lifeSpanObservation_2015.py is not in repo.  does it still exist?
the output file is available at https://gitlab.com/opencog-bio/bio-data/blob/master/scheme-representations/Lifespan-observations_2015-02-21.scm

**Comment by linas** [comment]
eddie has several long, giant branches that ere never merged into master.  Maybe its there?

Should his branches be merged?

Also, there's a whole mess of open bug reports ... I'm thinking these should be reviewed and disposed of as appropriate.

**Comment by mjsduncan** [comment]
the results of running the python file on this are stored in gitlab/opencog-bio/bio-data/scheme-representations.  i'm updating the R script to use the new version of this database download.

**Comment by eddiemonroe** [comment]
I think you've got it, Mike, but for clarity for others the Lifespan-observations_xxxx-xx-xx.csv file is from the Lifespan Observations Database project here http://lifespandb.sageweb.org/search?format=csv

Not part of this repo because it is data and it is regularly updated.

**Comment by mjsduncan** [comment]
i'll put the link in the knowledge-import/README.md but the raw data was
processed by the R script in the repo which is still broken for current
version :P
i'm working on it...
