### ISSUE TITLE
bioscience/opencog.conf needs updating for type system refactoring

### ISSUE THREAD

**Issue by mjsduncan** [opencog/agi-bio#66]
opencog.conf lists modules that aren't modules anymore.  probably a bunch of other stuff needs updating as well.

**Comment by linas** [comment]
Just copy and use this one: https://github.com/opencog/opencog/blob/master/lib/opencog.conf

in fact most of the stuff in there e.g ECAN is also not needed, but .. whatever.

**Comment by mjsduncan** [comment]
outdated
