### ISSUE TITLE
GO terms with empty name strings are being imported into the atomspace.

### ISSUE THREAD

**Issue by mjsduncan** [opencog/agi-bio#67]
this issue is mainly intended for icog folks with access to opencog-bio /bio-data gitlab repo but the python scripts that convert the public data files to scheme are here in agi-bio/knowledge-import.  after loading GO.scm and GO_annotations.scm generated per the README into an atomspace and using these functions from "GO utilities.scm":
```
(define GOname
    (lambda (GOterm)
        (gar
            (cog-execute!
                (GetLink
                    (EvaluationLink
                        (PredicateNode "GO_name")
                        (ListLink
                            GOterm
                            (VariableNode "$name"))))))))
                       
(define get-type-with-prefix
    (lambda (type string)
        (filter
            (lambda (atom) (string-prefix? string (cog-name atom)))
            (cog-get-atoms type))))
```
this procedure counts almost 2k GO terms with no ConceptNode associated
```
(length (filter
            (lambda (goterm) (eq? (list) (GOname goterm)))
            (get-type-with-prefix 'ConceptNode "GO:")))
$4 = 1976
```
the error could be in the python script or something missing in the original database downloads.

**Comment by linas** [comment]
fyi, if Goname is performance-senssitive, there are faster (but slightly more complex) ways of accomplishing what it does.

**Comment by mjsduncan** [comment]
there are cases where doing it faster would probably make a difference.  i
already want to replace this version because it creates an otherwise
useless one element set for each of the 47k GO terms and just adding an
erasure step will make it take even longer.  what are the other approaches?

**Comment by linas** [comment]
review the functions in here: https://github.com/opencog/atomspace/blob/master/opencog/scm/opencog/base/utilities.scm  - you probably want `cog-pred-get-partner `
```
(define-public (cog-pred-get-partner rel atom)
"
  cog-pred-get-partner -- Get the partner in an EvaluationLink
  cog-pred-get-partner pred atom
  Get the partner to the atom 'atom' in the opencog predicate 'pred'.
  An opencog predicate is assumed to be structured as follows:
     EvaluationLink
         SomeAtom  \"relation-name\"
         ListLink
             AnotherAtom  \"some atom\"
             AnotherAtom  \"some other atom\"
  Assuming this structure, then, given the top-level link, and one
  of the two atoms in the ListLink, this routine returns the other
  atom in the listLink.
"
```

There's also   `cog-get-pred`  at line 763

```
; ---------------------------------------------------------------------
(define-public (cog-get-pred inst pred-type)
"
  cog-get-pred -- Find all EvaluationLinks of given form.
  Return a list of predicates, of the given type, that an instance
  participates in.  'inst' must be an atom, and 'pred-type' must be
  an atom type.  That is, given a \"predicate\" of the form:
     EvaluationLink
        SomeAtom
        ListLink
            AnotherAtom \"abc\"
            GivenAtom \"def\"
  then, given the instance 'inst' (in this example, GivenAtom \"def\")
  and predicate type 'pred-type' 'SomeAtom, then this routine returns
  a list of all of the EvalutaionLink's in which 'inst' appears.
"
```

ughh this documentatin needs to be modernized.

**Comment by linas** [comment]
if the docummentation is hard to undertand, that is because its poorly written. More work needed to fix it.

**Comment by mjsduncan** [comment]
this import script has been retired
